print(str.partition('pão de cebola é bom, pão de queijo é mais', ','))
print(str.partition('o que aconteceu quando sep não é encontrado', 'x'))
print(str.join("X", "arara"))
print(str.split("arara", "r"))
print(str.replace("arara", "a", "r"))
print(str.rstrip(" X ") + str.lstrip(" Y "))
print(str.replace("teste de mesa"," ","#"))
print(str.join("#",str.split("teste de mesa")))
